name: Build
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build:
    name: Lint and tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14
          - 16
          - 18
          - latest
        architecture:
          - x64
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        architecture: ${{ matrix.architecture }}
    - run: yarn --frozen-lockfile
    - run: yarn lint
    - run: yarn test
